// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView1, lv_pct(100));
    lv_obj_set_height(ui_TabView1, lv_pct(100));
    lv_obj_set_x(ui_TabView1, -1);
    lv_obj_set_y(ui_TabView1, -1);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView1), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0xFFFFFF),
                                LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabView1), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_PinVolTabPage = lv_tabview_add_tab(ui_TabView1, "PinVol");
    lv_obj_set_style_bg_color(ui_PinVolTabPage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PinVolTabPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PinVolTabPage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PinVolTabPage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PinVolTabPage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PinVolTabPage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PinVolTabPage, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PinVolTabPage, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Panel14 = lv_obj_create(ui_PinVolTabPage);
    lv_obj_set_width(ui_Panel14, lv_pct(100));
    lv_obj_set_height(ui_Panel14, lv_pct(100));
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel14, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel14, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leftPanel19 = lv_obj_create(ui_Panel14);
    lv_obj_set_width(ui_leftPanel19, lv_pct(50));
    lv_obj_set_height(ui_leftPanel19, lv_pct(100));
    lv_obj_set_x(ui_leftPanel19, -1);
    lv_obj_set_y(ui_leftPanel19, 1);
    lv_obj_set_align(ui_leftPanel19, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_leftPanel19, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_leftPanel19, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_leftPanel19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_leftPanel19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_leftPanel19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_leftPanel19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_leftPanel19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_leftPanel19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_leftPanel19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_leftPanel19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_leftPanel19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pinvolglobal = lv_obj_create(ui_leftPanel19);
    lv_obj_set_width(ui_pinvolglobal, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_pinvolglobal, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_pinvolglobal, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_pinvolglobal, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_pinvolglobal, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pinvolglobal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pinvolglobal, lv_color_hex(0x4315ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pinvolglobal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pinvolglobal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pinvolglobal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pinvolglobal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pinvolglobal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pinvolglobal, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel22 = lv_obj_create(ui_pinvolglobal);
    lv_obj_set_width(ui_Panel22, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Panel22, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Panel22, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel22, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel22, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel22, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_Panel22);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "Global");
    lv_obj_set_style_text_color(ui_Label34, lv_color_hex(0xCDD9E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label34, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label34, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label34, lv_color_hex(0x2C0CA4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label34, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label34, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label34, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label34, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel21 = lv_obj_create(ui_pinvolglobal);
    lv_obj_set_width(ui_Panel21, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Panel21, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Panel21, 187);
    lv_obj_set_y(ui_Panel21, 93);
    lv_obj_set_align(ui_Panel21, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel21, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel21, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel21, lv_color_hex(0x4315ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel24 = lv_obj_create(ui_Panel21);
    lv_obj_set_width(ui_Panel24, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Panel24, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Panel24, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel24, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel24, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel24, lv_color_hex(0x4315ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pinvolGlobalUpImgButton = lv_imgbtn_create(ui_Panel24);
    lv_imgbtn_set_src(ui_pinvolGlobalUpImgButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_volume_normal_icon_64_png, NULL);
    lv_imgbtn_set_src(ui_pinvolGlobalUpImgButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_volume_normal_icon_64_pressed_png,
                      NULL);
    lv_obj_set_height(ui_pinvolGlobalUpImgButton, 64);
    lv_obj_set_width(ui_pinvolGlobalUpImgButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_pinvolGlobalUpImgButton, LV_ALIGN_CENTER);

    ui_Label39 = lv_label_create(ui_Panel24);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "VolUp");
    lv_obj_set_style_text_color(ui_Label39, lv_color_hex(0x261919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label39, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel25 = lv_obj_create(ui_Panel21);
    lv_obj_set_width(ui_Panel25, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Panel25, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Panel25, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel25, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel25, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel25, lv_color_hex(0x4315ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pinvolGlobalDownImgButton = lv_imgbtn_create(ui_Panel25);
    lv_imgbtn_set_src(ui_pinvolGlobalDownImgButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_volume_normal_red_icon_64_png,
                      NULL);
    lv_imgbtn_set_src(ui_pinvolGlobalDownImgButton, LV_IMGBTN_STATE_PRESSED, NULL,
                      &ui_img_volume_normal_red_icon_64_pressed_png, NULL);
    lv_obj_set_height(ui_pinvolGlobalDownImgButton, 64);
    lv_obj_set_width(ui_pinvolGlobalDownImgButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_pinvolGlobalDownImgButton, LV_ALIGN_CENTER);

    ui_Label40 = lv_label_create(ui_Panel25);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "VolDown");
    lv_obj_set_style_text_color(ui_Label40, lv_color_hex(0x261919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label40, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel26 = lv_obj_create(ui_Panel21);
    lv_obj_set_width(ui_Panel26, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Panel26, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Panel26, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel26, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel26, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel26, lv_color_hex(0x4315ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pinvolGlobalMuteImgButton = lv_imgbtn_create(ui_Panel26);
    lv_imgbtn_set_src(ui_pinvolGlobalMuteImgButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_volume_disabled_icon_64_png,
                      NULL);
    lv_imgbtn_set_src(ui_pinvolGlobalMuteImgButton, LV_IMGBTN_STATE_PRESSED, NULL,
                      &ui_img_volume_disabled_icon_64_pressed_png, NULL);
    lv_obj_set_height(ui_pinvolGlobalMuteImgButton, 64);
    lv_obj_set_width(ui_pinvolGlobalMuteImgButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_pinvolGlobalMuteImgButton, LV_ALIGN_CENTER);

    ui_Label41 = lv_label_create(ui_Panel26);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "Mute");
    lv_obj_set_style_text_color(ui_Label41, lv_color_hex(0x261919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label41, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel23 = lv_obj_create(ui_Panel21);
    lv_obj_set_width(ui_Panel23, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Panel23, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Panel23, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel23, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel23, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel23, lv_color_hex(0x4315ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pinvolGlobalNightModeButton = lv_imgbtn_create(ui_Panel23);
    lv_imgbtn_set_src(ui_pinvolGlobalNightModeButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1661985963, NULL);
    lv_imgbtn_set_src(ui_pinvolGlobalNightModeButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_494244644, NULL);
    lv_obj_set_height(ui_pinvolGlobalNightModeButton, 64);
    lv_obj_set_width(ui_pinvolGlobalNightModeButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_pinvolGlobalNightModeButton, LV_ALIGN_CENTER);

    ui_Label35 = lv_label_create(ui_Panel23);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "Night Mode");
    lv_obj_set_style_text_color(ui_Label35, lv_color_hex(0x261919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label35, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pinvoltable = lv_obj_create(ui_leftPanel19);
    lv_obj_set_width(ui_pinvoltable, lv_pct(100));
    lv_obj_set_height(ui_pinvoltable, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_pinvoltable, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_pinvoltable, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_pinvoltable, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pinvoltable, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pinvoltable, lv_color_hex(0x4315ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pinvoltable, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pinvoltable, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pinvoltable, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pinvoltable, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pinvoltable, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pinvoltable, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pinvoltable, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_pinvoltable);
    lv_obj_set_width(ui_Panel2, lv_pct(100));
    lv_obj_set_height(ui_Panel2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x2C0CA4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Table");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xCDD9E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label1, lv_color_hex(0x2C0CA4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label1, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label1, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_pinvoltable);
    lv_obj_set_width(ui_Panel7, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Panel7, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Panel7, 187);
    lv_obj_set_y(ui_Panel7, 93);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x4315ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Panel7);
    lv_obj_set_width(ui_Panel8, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Panel8, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel8, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x4315ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pinvolTableVolUpImgButton = lv_imgbtn_create(ui_Panel8);
    lv_imgbtn_set_src(ui_pinvolTableVolUpImgButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_volume_normal_icon_64_png,
                      NULL);
    lv_imgbtn_set_src(ui_pinvolTableVolUpImgButton, LV_IMGBTN_STATE_PRESSED, NULL,
                      &ui_img_volume_normal_icon_64_pressed_png, NULL);
    lv_obj_set_height(ui_pinvolTableVolUpImgButton, 64);
    lv_obj_set_width(ui_pinvolTableVolUpImgButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_pinvolTableVolUpImgButton, LV_ALIGN_CENTER);

    ui_Label2 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "VolUp");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x261919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Panel7);
    lv_obj_set_width(ui_Panel9, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Panel9, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel9, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x4315ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pinvolTableVolDownImgButton = lv_imgbtn_create(ui_Panel9);
    lv_imgbtn_set_src(ui_pinvolTableVolDownImgButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_volume_normal_red_icon_64_png,
                      NULL);
    lv_imgbtn_set_src(ui_pinvolTableVolDownImgButton, LV_IMGBTN_STATE_PRESSED, NULL,
                      &ui_img_volume_normal_red_icon_64_pressed_png, NULL);
    lv_obj_set_height(ui_pinvolTableVolDownImgButton, 64);
    lv_obj_set_width(ui_pinvolTableVolDownImgButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_pinvolTableVolDownImgButton, LV_ALIGN_CENTER);

    ui_Label3 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "VolDown");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x261919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rightPanel10 = lv_obj_create(ui_Panel14);
    lv_obj_set_width(ui_rightPanel10, lv_pct(50));
    lv_obj_set_height(ui_rightPanel10, lv_pct(100));
    lv_obj_set_align(ui_rightPanel10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_rightPanel10, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_rightPanel10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_rightPanel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_rightPanel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rightPanel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rightPanel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rightPanel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_rightPanel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_rightPanel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_rightPanel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_rightPanel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pinvoltable1 = lv_obj_create(ui_rightPanel10);
    lv_obj_set_width(ui_pinvoltable1, lv_pct(98));
    lv_obj_set_height(ui_pinvoltable1, lv_pct(100));
    lv_obj_set_align(ui_pinvoltable1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_pinvoltable1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_pinvoltable1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_pinvoltable1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pinvoltable1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pinvoltable1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pinvoltable1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pinvoltable1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pinvoltable1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pinvoltable1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pinvoltable1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_pinvoltable1);
    lv_obj_set_width(ui_Panel10, lv_pct(100));
    lv_obj_set_height(ui_Panel10, lv_pct(100));
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel10, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel10, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x2C0CA4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel27 = lv_obj_create(ui_Panel10);
    lv_obj_set_width(ui_Panel27, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Panel27, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Panel27, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel27, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel27, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel27, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel27, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel27, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel27, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel27, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel27, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Panel27);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "SSF");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xCDD9E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label7, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label7, lv_color_hex(0x2C0CA4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label7, 160, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label7, 160, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_Panel10);
    lv_obj_set_width(ui_Panel11, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Panel11, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Panel11, 187);
    lv_obj_set_y(ui_Panel11, 93);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel11, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel11, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backglassPanel15 = lv_obj_create(ui_Panel11);
    lv_obj_set_width(ui_backglassPanel15, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_backglassPanel15, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_backglassPanel15, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_backglassPanel15, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_backglassPanel15, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_backglassPanel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backglassPanel15, lv_color_hex(0x4315ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backglassPanel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_backglassPanel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_backglassPanel15, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_backglassPanel15, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_backglassPanel15, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_backglassPanel15, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_backglassPanel15);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "BackGlass");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label10, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label10, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel12 = lv_obj_create(ui_backglassPanel15);
    lv_obj_set_width(ui_Panel12, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Panel12, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel12, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel12, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0x4315ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel12, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pinvolSSFBgUpImgButton = lv_imgbtn_create(ui_Panel12);
    lv_imgbtn_set_src(ui_pinvolSSFBgUpImgButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_volume_normal_icon_64_png, NULL);
    lv_imgbtn_set_src(ui_pinvolSSFBgUpImgButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_volume_normal_icon_64_pressed_png,
                      NULL);
    lv_obj_set_height(ui_pinvolSSFBgUpImgButton, 64);
    lv_obj_set_width(ui_pinvolSSFBgUpImgButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_pinvolSSFBgUpImgButton, LV_ALIGN_CENTER);

    ui_Label8 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "VolUp");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x261919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_backglassPanel15);
    lv_obj_set_width(ui_Panel13, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Panel13, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel13, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel13, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0x4315ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pinvolSSFBgDownImgButton = lv_imgbtn_create(ui_Panel13);
    lv_imgbtn_set_src(ui_pinvolSSFBgDownImgButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_volume_normal_red_icon_64_png,
                      NULL);
    lv_imgbtn_set_src(ui_pinvolSSFBgDownImgButton, LV_IMGBTN_STATE_PRESSED, NULL,
                      &ui_img_volume_normal_red_icon_64_pressed_png, NULL);
    lv_obj_set_height(ui_pinvolSSFBgDownImgButton, 64);
    lv_obj_set_width(ui_pinvolSSFBgDownImgButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_pinvolSSFBgDownImgButton, LV_ALIGN_CENTER);

    ui_Label9 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "VolDown");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x261919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel15 = lv_obj_create(ui_Panel10);
    lv_obj_set_width(ui_Panel15, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Panel15, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Panel15, 187);
    lv_obj_set_y(ui_Panel15, 93);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel15, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel15, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backglassPanel1 = lv_obj_create(ui_Panel15);
    lv_obj_set_width(ui_backglassPanel1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_backglassPanel1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_backglassPanel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_backglassPanel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_backglassPanel1, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_backglassPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backglassPanel1, lv_color_hex(0x4315ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backglassPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_backglassPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_backglassPanel1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_backglassPanel1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_backglassPanel1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_backglassPanel1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_backglassPanel1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Rear");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label11, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label11, 95, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel16 = lv_obj_create(ui_backglassPanel1);
    lv_obj_set_width(ui_Panel16, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Panel16, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel16, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel16, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0x4315ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel16, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pinvolSSFRearUpImgButton = lv_imgbtn_create(ui_Panel16);
    lv_imgbtn_set_src(ui_pinvolSSFRearUpImgButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_volume_normal_icon_64_png, NULL);
    lv_imgbtn_set_src(ui_pinvolSSFRearUpImgButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_volume_normal_icon_64_pressed_png,
                      NULL);
    lv_obj_set_height(ui_pinvolSSFRearUpImgButton, 64);
    lv_obj_set_width(ui_pinvolSSFRearUpImgButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_pinvolSSFRearUpImgButton, LV_ALIGN_CENTER);

    ui_Label12 = lv_label_create(ui_Panel16);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "VolUp");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x261919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel17 = lv_obj_create(ui_backglassPanel1);
    lv_obj_set_width(ui_Panel17, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Panel17, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel17, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel17, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0x4315ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pinvolSSFRearDownImgButton = lv_imgbtn_create(ui_Panel17);
    lv_imgbtn_set_src(ui_pinvolSSFRearDownImgButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_volume_normal_red_icon_64_png,
                      NULL);
    lv_imgbtn_set_src(ui_pinvolSSFRearDownImgButton, LV_IMGBTN_STATE_PRESSED, NULL,
                      &ui_img_volume_normal_red_icon_64_pressed_png, NULL);
    lv_obj_set_height(ui_pinvolSSFRearDownImgButton, 64);
    lv_obj_set_width(ui_pinvolSSFRearDownImgButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_pinvolSSFRearDownImgButton, LV_ALIGN_CENTER);

    ui_Label13 = lv_label_create(ui_Panel17);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "VolDown");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x261919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel18 = lv_obj_create(ui_Panel10);
    lv_obj_set_width(ui_Panel18, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Panel18, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Panel18, 187);
    lv_obj_set_y(ui_Panel18, 93);
    lv_obj_set_align(ui_Panel18, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel18, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel18, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backglassPanel2 = lv_obj_create(ui_Panel18);
    lv_obj_set_width(ui_backglassPanel2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_backglassPanel2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_backglassPanel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_backglassPanel2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_backglassPanel2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_backglassPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backglassPanel2, lv_color_hex(0x4315ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backglassPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_backglassPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_backglassPanel2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_backglassPanel2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_backglassPanel2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_backglassPanel2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_backglassPanel2);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Front");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label14, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label14, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel19 = lv_obj_create(ui_backglassPanel2);
    lv_obj_set_width(ui_Panel19, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Panel19, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Panel19, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel19, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel19, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel19, lv_color_hex(0x4315ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel19, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pinvolSSFFrontUpImgButton = lv_imgbtn_create(ui_Panel19);
    lv_imgbtn_set_src(ui_pinvolSSFFrontUpImgButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_volume_normal_icon_64_png,
                      NULL);
    lv_imgbtn_set_src(ui_pinvolSSFFrontUpImgButton, LV_IMGBTN_STATE_PRESSED, NULL,
                      &ui_img_volume_normal_icon_64_pressed_png, NULL);
    lv_obj_set_height(ui_pinvolSSFFrontUpImgButton, 64);
    lv_obj_set_width(ui_pinvolSSFFrontUpImgButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_pinvolSSFFrontUpImgButton, LV_ALIGN_CENTER);

    ui_Label15 = lv_label_create(ui_Panel19);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "VolUp");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x261919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel20 = lv_obj_create(ui_backglassPanel2);
    lv_obj_set_width(ui_Panel20, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Panel20, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Panel20, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel20, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel20, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel20, lv_color_hex(0x4315ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pinvolSSFFrontDownImgButton = lv_imgbtn_create(ui_Panel20);
    lv_imgbtn_set_src(ui_pinvolSSFFrontDownImgButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_volume_normal_red_icon_64_png,
                      NULL);
    lv_imgbtn_set_src(ui_pinvolSSFFrontDownImgButton, LV_IMGBTN_STATE_PRESSED, NULL,
                      &ui_img_volume_normal_red_icon_64_pressed_png, NULL);
    lv_obj_set_height(ui_pinvolSSFFrontDownImgButton, 64);
    lv_obj_set_width(ui_pinvolSSFFrontDownImgButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_pinvolSSFFrontDownImgButton, LV_ALIGN_CENTER);

    ui_Label16 = lv_label_create(ui_Panel20);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "VolDown");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x261919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PinMameTabPage = lv_tabview_add_tab(ui_TabView1, "PinMame");
    lv_obj_set_style_bg_color(ui_PinMameTabPage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PinMameTabPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PinMameTabPage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PinMameTabPage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PinMameTabPage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PinMameTabPage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PinMameTabPage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_PinMameTabPage, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PinMameTabPage, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PinMameTabPage, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PinMameTabPage, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Panel30 = lv_obj_create(ui_PinMameTabPage);
    lv_obj_set_width(ui_Panel30, lv_pct(100));
    lv_obj_set_height(ui_Panel30, lv_pct(100));
    lv_obj_set_align(ui_Panel30, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel30, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel30, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel30, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leftPanel = lv_obj_create(ui_Panel30);
    lv_obj_set_width(ui_leftPanel, lv_pct(50));
    lv_obj_set_height(ui_leftPanel, lv_pct(100));
    lv_obj_set_align(ui_leftPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_leftPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_leftPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_leftPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_leftPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_leftPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_leftPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_leftPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_leftPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_leftPanel);
    lv_obj_set_width(ui_Panel3, lv_pct(100));
    lv_obj_set_height(ui_Panel3, lv_pct(100));
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Panel3);
    lv_obj_set_width(ui_Panel4, lv_pct(100));
    lv_obj_set_height(ui_Panel4, lv_pct(25));
    lv_obj_set_x(ui_Panel4, 0);
    lv_obj_set_y(ui_Panel4, 2);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pinmameEBBuyinButton = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_pinmameEBBuyinButton, 100);
    lv_obj_set_height(ui_pinmameEBBuyinButton, 75);
    lv_obj_set_align(ui_pinmameEBBuyinButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pinmameEBBuyinButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pinmameEBBuyinButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_pinmameEBBuyinButton);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "EB Buyin");

    ui_pinmameCoin3Button = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_pinmameCoin3Button, 100);
    lv_obj_set_height(ui_pinmameCoin3Button, 75);
    lv_obj_set_align(ui_pinmameCoin3Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pinmameCoin3Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pinmameCoin3Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_pinmameCoin3Button);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Coin 3");

    ui_pinmameCoin4Button = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_pinmameCoin4Button, 100);
    lv_obj_set_height(ui_pinmameCoin4Button, 75);
    lv_obj_set_align(ui_pinmameCoin4Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pinmameCoin4Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pinmameCoin4Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_pinmameCoin4Button);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Coin 4\nReset HS");
    lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Panel3);
    lv_obj_set_width(ui_Panel6, lv_pct(100));
    lv_obj_set_height(ui_Panel6, lv_pct(75));
    lv_obj_set_x(ui_Panel6, -56);
    lv_obj_set_y(ui_Panel6, 90);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel28 = lv_obj_create(ui_Panel6);
    lv_obj_set_width(ui_Panel28, lv_pct(100));
    lv_obj_set_height(ui_Panel28, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Panel28, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel28, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel28, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel28, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel28, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel28, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pinmameUpButton = lv_btn_create(ui_Panel28);
    lv_obj_set_width(ui_pinmameUpButton, 100);
    lv_obj_set_height(ui_pinmameUpButton, 75);
    lv_obj_set_align(ui_pinmameUpButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pinmameUpButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pinmameUpButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_pinmameUpButton);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "UP");

    ui_pinmameDownButton = lv_btn_create(ui_Panel28);
    lv_obj_set_width(ui_pinmameDownButton, 100);
    lv_obj_set_height(ui_pinmameDownButton, 75);
    lv_obj_set_align(ui_pinmameDownButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pinmameDownButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pinmameDownButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label19 = lv_label_create(ui_pinmameDownButton);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Down");

    ui_Panel5 = lv_obj_create(ui_Panel6);
    lv_obj_set_width(ui_Panel5, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Panel5, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pinmameDoorButton = lv_btn_create(ui_Panel5);
    lv_obj_set_width(ui_pinmameDoorButton, 100);
    lv_obj_set_height(ui_pinmameDoorButton, 75);
    lv_obj_set_align(ui_pinmameDoorButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pinmameDoorButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pinmameDoorButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_pinmameDoorButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pinmameDoorButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_pinmameDoorButton);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Door\nOpen/Close");
    lv_obj_set_style_text_align(ui_Label17, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel29 = lv_obj_create(ui_Panel6);
    lv_obj_set_width(ui_Panel29, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Panel29, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Panel29, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel29, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel29, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel29, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel29, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pinmameEnterButton = lv_btn_create(ui_Panel29);
    lv_obj_set_width(ui_pinmameEnterButton, 100);
    lv_obj_set_height(ui_pinmameEnterButton, 75);
    lv_obj_set_align(ui_pinmameEnterButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pinmameEnterButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pinmameEnterButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_pinmameEnterButton);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Enter");

    ui_pinmameCancelButton = lv_btn_create(ui_Panel29);
    lv_obj_set_width(ui_pinmameCancelButton, 100);
    lv_obj_set_height(ui_pinmameCancelButton, 75);
    lv_obj_set_align(ui_pinmameCancelButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pinmameCancelButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pinmameCancelButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label21 = lv_label_create(ui_pinmameCancelButton);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Cancel");

    ui_rightPanel = lv_obj_create(ui_Panel30);
    lv_obj_set_width(ui_rightPanel, lv_pct(50));
    lv_obj_set_height(ui_rightPanel, lv_pct(100));
    lv_obj_set_align(ui_rightPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_rightPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_rightPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_rightPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_rightPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rightPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rightPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_rightPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_rightPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_rightPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_rightPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel31 = lv_obj_create(ui_rightPanel);
    lv_obj_set_width(ui_Panel31, lv_pct(98));
    lv_obj_set_height(ui_Panel31, lv_pct(100));
    lv_obj_set_align(ui_Panel31, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel31, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel31, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel31, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel31, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel31, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel31, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel31, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel31, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leftPanel1 = lv_obj_create(ui_Panel31);
    lv_obj_set_width(ui_leftPanel1, lv_pct(48));
    lv_obj_set_height(ui_leftPanel1, lv_pct(100));
    lv_obj_set_align(ui_leftPanel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_leftPanel1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_leftPanel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_leftPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_leftPanel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_leftPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_leftPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_leftPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_leftPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_leftPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_leftPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pinmameShowOptsButton = lv_btn_create(ui_leftPanel1);
    lv_obj_set_width(ui_pinmameShowOptsButton, lv_pct(100));
    lv_obj_set_height(ui_pinmameShowOptsButton, lv_pct(15));
    lv_obj_set_align(ui_pinmameShowOptsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pinmameShowOptsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pinmameShowOptsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label22 = lv_label_create(ui_pinmameShowOptsButton);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Show Options");

    ui_pinmameResetEmuButton = lv_btn_create(ui_leftPanel1);
    lv_obj_set_width(ui_pinmameResetEmuButton, lv_pct(100));
    lv_obj_set_height(ui_pinmameResetEmuButton, lv_pct(15));
    lv_obj_set_align(ui_pinmameResetEmuButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pinmameResetEmuButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pinmameResetEmuButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label24 = lv_label_create(ui_pinmameResetEmuButton);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "Reset Emulation");

    ui_pinmameWindowLockButton = lv_btn_create(ui_leftPanel1);
    lv_obj_set_width(ui_pinmameWindowLockButton, lv_pct(100));
    lv_obj_set_height(ui_pinmameWindowLockButton, lv_pct(15));
    lv_obj_set_align(ui_pinmameWindowLockButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pinmameWindowLockButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pinmameWindowLockButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label25 = lv_label_create(ui_pinmameWindowLockButton);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "Window Lock");

    ui_Label26 = lv_label_create(ui_pinmameWindowLockButton);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Window Lock");

    ui_pinmameDisplaySizeButton = lv_btn_create(ui_leftPanel1);
    lv_obj_set_width(ui_pinmameDisplaySizeButton, lv_pct(100));
    lv_obj_set_height(ui_pinmameDisplaySizeButton, lv_pct(15));
    lv_obj_set_align(ui_pinmameDisplaySizeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pinmameDisplaySizeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pinmameDisplaySizeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label27 = lv_label_create(ui_pinmameDisplaySizeButton);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "Display Size");

    ui_rightPanel22 = lv_obj_create(ui_Panel31);
    lv_obj_set_width(ui_rightPanel22, lv_pct(48));
    lv_obj_set_height(ui_rightPanel22, lv_pct(100));
    lv_obj_set_align(ui_rightPanel22, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_rightPanel22, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_rightPanel22, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_rightPanel22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_rightPanel22, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rightPanel22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rightPanel22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_rightPanel22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_rightPanel22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_rightPanel22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_rightPanel22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pinmameShowKeysButton = lv_btn_create(ui_rightPanel22);
    lv_obj_set_width(ui_pinmameShowKeysButton, lv_pct(100));
    lv_obj_set_height(ui_pinmameShowKeysButton, lv_pct(15));
    lv_obj_set_align(ui_pinmameShowKeysButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pinmameShowKeysButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pinmameShowKeysButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label36 = lv_label_create(ui_pinmameShowKeysButton);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label36, 0);
    lv_obj_set_y(ui_Label36, -1);
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "Show Keys");

    ui_pinmameDipButton = lv_btn_create(ui_rightPanel22);
    lv_obj_set_width(ui_pinmameDipButton, lv_pct(100));
    lv_obj_set_height(ui_pinmameDipButton, lv_pct(15));
    lv_obj_set_align(ui_pinmameDipButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pinmameDipButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pinmameDipButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label23 = lv_label_create(ui_pinmameDipButton);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 0);
    lv_obj_set_y(ui_Label23, -1);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "DIP Switch");

    ui_pinmameAddEBallButton = lv_btn_create(ui_rightPanel22);
    lv_obj_set_width(ui_pinmameAddEBallButton, lv_pct(100));
    lv_obj_set_height(ui_pinmameAddEBallButton, lv_pct(15));
    lv_obj_set_align(ui_pinmameAddEBallButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pinmameAddEBallButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pinmameAddEBallButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label28 = lv_label_create(ui_pinmameAddEBallButton);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, 0);
    lv_obj_set_y(ui_Label28, -1);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "Add Extra Ball");

    ui_pinmameBangBackButton = lv_btn_create(ui_rightPanel22);
    lv_obj_set_width(ui_pinmameBangBackButton, lv_pct(100));
    lv_obj_set_height(ui_pinmameBangBackButton, lv_pct(15));
    lv_obj_set_align(ui_pinmameBangBackButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pinmameBangBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pinmameBangBackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label29 = lv_label_create(ui_pinmameBangBackButton);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, 0);
    lv_obj_set_y(ui_Label29, -1);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "Bang Back");

    ui_VPXTabPage = lv_tabview_add_tab(ui_TabView1, "VPX");

    ui_StatusTabPage = lv_tabview_add_tab(ui_TabView1, "Status");
    lv_obj_set_style_bg_color(ui_StatusTabPage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StatusTabPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_StatusTabPage);
    lv_obj_set_width(ui_Panel1, lv_pct(100));
    lv_obj_set_height(ui_Panel1, lv_pct(100));
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel34 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_Panel34, lv_pct(100));
    lv_obj_set_height(ui_Panel34, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Panel34, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel34, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel34, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel34, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel34, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel34, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel34, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel34, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel34, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel36 = lv_obj_create(ui_Panel34);
    lv_obj_set_width(ui_Panel36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Panel36, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Panel36, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel36, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel36, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel36, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel36, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel35 = lv_obj_create(ui_Panel36);
    lv_obj_set_width(ui_Panel35, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Panel35, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Panel35, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel35, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel35, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel35, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel35, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel35, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel35, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel35, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel35, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel35, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_Panel35);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "Device Name:");
    lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_deviceNameLabel = lv_label_create(ui_Panel35);
    lv_obj_set_width(ui_deviceNameLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_deviceNameLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_deviceNameLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_deviceNameLabel, ".....");
    lv_obj_set_style_text_color(ui_deviceNameLabel, lv_color_hex(0xFE5858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_deviceNameLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel32 = lv_obj_create(ui_Panel36);
    lv_obj_set_width(ui_Panel32, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Panel32, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Panel32, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel32, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel32, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel32, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel32, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel32, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel32, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel32, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel32, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_Panel32);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "Cabinet Temp:");
    lv_obj_set_style_text_color(ui_Label31, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label31, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label31, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cabinetTempLabel = lv_label_create(ui_Panel32);
    lv_obj_set_width(ui_cabinetTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cabinetTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_cabinetTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cabinetTempLabel, "......");
    lv_obj_set_style_text_color(ui_cabinetTempLabel, lv_color_hex(0xFE5858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cabinetTempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_cabinetTempLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cabinetTempLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cabinetTempLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cabinetTempLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_cabinetTempLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_cabinetTempLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_Panel32);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "C");
    lv_obj_set_style_text_color(ui_Label30, lv_color_hex(0xFE5858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel33 = lv_obj_create(ui_Panel34);
    lv_obj_set_width(ui_Panel33, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Panel33, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Panel33, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel33, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel33, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel33, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel33, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiStatusImg = lv_img_create(ui_Panel33);
    lv_img_set_src(ui_WiFiStatusImg, &ui_img_red_wifi_64_png);
    lv_obj_set_width(ui_WiFiStatusImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiStatusImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WiFiStatusImg, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_WiFiStatusImg, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_WiFiStatusImg, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_WiFiStatusImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WiFiStatusImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ssidLabel = lv_label_create(ui_Panel33);
    lv_obj_set_width(ui_ssidLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ssidLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ssidLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ssidLabel, ".......");
    lv_obj_set_style_text_color(ui_ssidLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ssidLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statusMsgsTextArea = lv_textarea_create(ui_Panel1);
    lv_obj_set_width(ui_statusMsgsTextArea, lv_pct(100));
    lv_obj_set_height(ui_statusMsgsTextArea, lv_pct(55));
    lv_obj_set_align(ui_statusMsgsTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_statusMsgsTextArea, "No Messages");
    lv_obj_set_style_text_color(ui_statusMsgsTextArea, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_statusMsgsTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_statusMsgsTextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_statusMsgsTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel37 = lv_obj_create(ui_Panel1);
    lv_obj_set_height(ui_Panel37, 50);
    lv_obj_set_width(ui_Panel37, lv_pct(100));
    lv_obj_set_align(ui_Panel37, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel37, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel37, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel37, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel37, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel37, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statusPingButton = lv_btn_create(ui_Panel37);
    lv_obj_set_width(ui_statusPingButton, 100);
    lv_obj_set_height(ui_statusPingButton, 50);
    lv_obj_set_align(ui_statusPingButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_statusPingButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_statusPingButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label33 = lv_label_create(ui_statusPingButton);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "Ping Contr");

    lv_obj_add_event_cb(ui_pinvolGlobalUpImgButton, ui_event_pinvolGlobalUpImgButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinvolGlobalDownImgButton, ui_event_pinvolGlobalDownImgButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinvolGlobalMuteImgButton, ui_event_pinvolGlobalMuteImgButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinvolGlobalNightModeButton, ui_event_pinvolGlobalNightModeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinvolTableVolUpImgButton, ui_event_pinvolTableVolUpImgButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinvolTableVolDownImgButton, ui_event_pinvolTableVolDownImgButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinvolSSFBgUpImgButton, ui_event_pinvolSSFBgUpImgButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinvolSSFBgDownImgButton, ui_event_pinvolSSFBgDownImgButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinvolSSFRearUpImgButton, ui_event_pinvolSSFRearUpImgButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinvolSSFRearDownImgButton, ui_event_pinvolSSFRearDownImgButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinvolSSFFrontUpImgButton, ui_event_pinvolSSFFrontUpImgButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinvolSSFFrontDownImgButton, ui_event_pinvolSSFFrontDownImgButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinmameEBBuyinButton, ui_event_pinmameEBBuyinButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinmameCoin3Button, ui_event_pinmameCoin3Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinmameCoin4Button, ui_event_pinmameCoin4Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinmameUpButton, ui_event_pinmameUpButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinmameDownButton, ui_event_pinmameDownButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinmameDoorButton, ui_event_pinmameDoorButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinmameEnterButton, ui_event_pinmameEnterButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinmameCancelButton, ui_event_pinmameCancelButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinmameShowOptsButton, ui_event_pinmameShowOptsButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinmameResetEmuButton, ui_event_pinmameResetEmuButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinmameWindowLockButton, ui_event_pinmameWindowLockButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinmameDisplaySizeButton, ui_event_pinmameDisplaySizeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinmameShowKeysButton, ui_event_pinmameShowKeysButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinmameDipButton, ui_event_pinmameDipButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinmameAddEBallButton, ui_event_pinmameAddEBallButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pinmameBangBackButton, ui_event_pinmameBangBackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_statusPingButton, ui_event_statusPingButton, LV_EVENT_ALL, NULL);

}
