// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_PinVolTabPage;
lv_obj_t * ui_Panel14;
lv_obj_t * ui_leftPanel19;
lv_obj_t * ui_pinvolglobal;
lv_obj_t * ui_Panel22;
lv_obj_t * ui_Label34;
lv_obj_t * ui_Panel21;
lv_obj_t * ui_Panel24;
void ui_event_pinvolGlobalUpImgButton(lv_event_t * e);
lv_obj_t * ui_pinvolGlobalUpImgButton;
lv_obj_t * ui_Label39;
lv_obj_t * ui_Panel25;
void ui_event_pinvolGlobalDownImgButton(lv_event_t * e);
lv_obj_t * ui_pinvolGlobalDownImgButton;
lv_obj_t * ui_Label40;
lv_obj_t * ui_Panel26;
void ui_event_pinvolGlobalMuteImgButton(lv_event_t * e);
lv_obj_t * ui_pinvolGlobalMuteImgButton;
lv_obj_t * ui_Label41;
lv_obj_t * ui_Panel23;
void ui_event_pinvolGlobalNightModeButton(lv_event_t * e);
lv_obj_t * ui_pinvolGlobalNightModeButton;
lv_obj_t * ui_Label35;
lv_obj_t * ui_pinvoltable;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Panel8;
void ui_event_pinvolTableVolUpImgButton(lv_event_t * e);
lv_obj_t * ui_pinvolTableVolUpImgButton;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Panel9;
void ui_event_pinvolTableVolDownImgButton(lv_event_t * e);
lv_obj_t * ui_pinvolTableVolDownImgButton;
lv_obj_t * ui_Label3;
lv_obj_t * ui_rightPanel10;
lv_obj_t * ui_pinvoltable1;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Panel27;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_backglassPanel15;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Panel12;
void ui_event_pinvolSSFBgUpImgButton(lv_event_t * e);
lv_obj_t * ui_pinvolSSFBgUpImgButton;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Panel13;
void ui_event_pinvolSSFBgDownImgButton(lv_event_t * e);
lv_obj_t * ui_pinvolSSFBgDownImgButton;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Panel15;
lv_obj_t * ui_backglassPanel1;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Panel16;
void ui_event_pinvolSSFRearUpImgButton(lv_event_t * e);
lv_obj_t * ui_pinvolSSFRearUpImgButton;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Panel17;
void ui_event_pinvolSSFRearDownImgButton(lv_event_t * e);
lv_obj_t * ui_pinvolSSFRearDownImgButton;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Panel18;
lv_obj_t * ui_backglassPanel2;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Panel19;
void ui_event_pinvolSSFFrontUpImgButton(lv_event_t * e);
lv_obj_t * ui_pinvolSSFFrontUpImgButton;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Panel20;
void ui_event_pinvolSSFFrontDownImgButton(lv_event_t * e);
lv_obj_t * ui_pinvolSSFFrontDownImgButton;
lv_obj_t * ui_Label16;
lv_obj_t * ui_PinMameTabPage;
lv_obj_t * ui_Panel30;
lv_obj_t * ui_leftPanel;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Panel4;
void ui_event_pinmameEBBuyinButton(lv_event_t * e);
lv_obj_t * ui_pinmameEBBuyinButton;
lv_obj_t * ui_Label4;
void ui_event_pinmameCoin3Button(lv_event_t * e);
lv_obj_t * ui_pinmameCoin3Button;
lv_obj_t * ui_Label5;
void ui_event_pinmameCoin4Button(lv_event_t * e);
lv_obj_t * ui_pinmameCoin4Button;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Panel28;
void ui_event_pinmameUpButton(lv_event_t * e);
lv_obj_t * ui_pinmameUpButton;
lv_obj_t * ui_Label18;
void ui_event_pinmameDownButton(lv_event_t * e);
lv_obj_t * ui_pinmameDownButton;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Panel5;
void ui_event_pinmameDoorButton(lv_event_t * e);
lv_obj_t * ui_pinmameDoorButton;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Panel29;
void ui_event_pinmameEnterButton(lv_event_t * e);
lv_obj_t * ui_pinmameEnterButton;
lv_obj_t * ui_Label20;
void ui_event_pinmameCancelButton(lv_event_t * e);
lv_obj_t * ui_pinmameCancelButton;
lv_obj_t * ui_Label21;
lv_obj_t * ui_rightPanel;
lv_obj_t * ui_Panel31;
lv_obj_t * ui_leftPanel1;
void ui_event_pinmameShowOptsButton(lv_event_t * e);
lv_obj_t * ui_pinmameShowOptsButton;
lv_obj_t * ui_Label22;
void ui_event_pinmameResetEmuButton(lv_event_t * e);
lv_obj_t * ui_pinmameResetEmuButton;
lv_obj_t * ui_Label24;
void ui_event_pinmameWindowLockButton(lv_event_t * e);
lv_obj_t * ui_pinmameWindowLockButton;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Label26;
void ui_event_pinmameDisplaySizeButton(lv_event_t * e);
lv_obj_t * ui_pinmameDisplaySizeButton;
lv_obj_t * ui_Label27;
lv_obj_t * ui_rightPanel22;
void ui_event_pinmameShowKeysButton(lv_event_t * e);
lv_obj_t * ui_pinmameShowKeysButton;
lv_obj_t * ui_Label36;
void ui_event_pinmameDipButton(lv_event_t * e);
lv_obj_t * ui_pinmameDipButton;
lv_obj_t * ui_Label23;
void ui_event_pinmameAddEBallButton(lv_event_t * e);
lv_obj_t * ui_pinmameAddEBallButton;
lv_obj_t * ui_Label28;
void ui_event_pinmameBangBackButton(lv_event_t * e);
lv_obj_t * ui_pinmameBangBackButton;
lv_obj_t * ui_Label29;
lv_obj_t * ui_VPXTabPage;
lv_obj_t * ui_StatusTabPage;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Panel34;
lv_obj_t * ui_Panel36;
lv_obj_t * ui_Panel35;
lv_obj_t * ui_Label32;
lv_obj_t * ui_deviceNameLabel;
lv_obj_t * ui_Panel32;
lv_obj_t * ui_Label31;
lv_obj_t * ui_cabinetTempLabel;
lv_obj_t * ui_Label30;
lv_obj_t * ui_Panel33;
lv_obj_t * ui_WiFiStatusImg;
lv_obj_t * ui_ssidLabel;
lv_obj_t * ui_statusMsgsTextArea;
lv_obj_t * ui_Panel37;
void ui_event_statusPingButton(lv_event_t * e);
lv_obj_t * ui_statusPingButton;
lv_obj_t * ui_Label33;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_1984605205[1] = {&ui_img_1661985963};
const lv_img_dsc_t * ui_imgset_green_wifi_[1] = {&ui_img_green_wifi_64_png};
const lv_img_dsc_t * ui_imgset_red_wifi_[1] = {&ui_img_red_wifi_64_png};
const lv_img_dsc_t * ui_imgset_volume_disabled_icon_[1] = {&ui_img_volume_disabled_icon_64_png};
const lv_img_dsc_t * ui_imgset_volume_normal_icon_[1] = {&ui_img_volume_normal_icon_64_png};
const lv_img_dsc_t * ui_imgset_volume_normal_red_icon_[1] = {&ui_img_volume_normal_red_icon_64_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_pinvolGlobalUpImgButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinvolEvent_cb(e);
    }
}
void ui_event_pinvolGlobalDownImgButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinvolEvent_cb(e);
    }
}
void ui_event_pinvolGlobalMuteImgButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinvolEvent_cb(e);
    }
}
void ui_event_pinvolGlobalNightModeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinvolEvent_cb(e);
    }
}
void ui_event_pinvolTableVolUpImgButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinvolEvent_cb(e);
    }
}
void ui_event_pinvolTableVolDownImgButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinvolEvent_cb(e);
    }
}
void ui_event_pinvolSSFBgUpImgButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinvolEvent_cb(e);
    }
}
void ui_event_pinvolSSFBgDownImgButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinvolEvent_cb(e);
    }
}
void ui_event_pinvolSSFRearUpImgButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinvolEvent_cb(e);
    }
}
void ui_event_pinvolSSFRearDownImgButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinvolEvent_cb(e);
    }
}
void ui_event_pinvolSSFFrontUpImgButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinvolEvent_cb(e);
    }
}
void ui_event_pinvolSSFFrontDownImgButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinvolEvent_cb(e);
    }
}
void ui_event_pinmameEBBuyinButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinmameEvent_cb(e);
    }
}
void ui_event_pinmameCoin3Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinmameEvent_cb(e);
    }
}
void ui_event_pinmameCoin4Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinmameEvent_cb(e);
    }
}
void ui_event_pinmameUpButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinmameEvent_cb(e);
    }
}
void ui_event_pinmameDownButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinmameEvent_cb(e);
    }
}
void ui_event_pinmameDoorButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinmameEvent_cb(e);
    }
}
void ui_event_pinmameEnterButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinmameEvent_cb(e);
    }
}
void ui_event_pinmameCancelButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinmameEvent_cb(e);
    }
}
void ui_event_pinmameShowOptsButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinmameEvent_cb(e);
    }
}
void ui_event_pinmameResetEmuButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinmameEvent_cb(e);
    }
}
void ui_event_pinmameWindowLockButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinmameEvent_cb(e);
    }
}
void ui_event_pinmameDisplaySizeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinmameEvent_cb(e);
    }
}
void ui_event_pinmameShowKeysButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinmameEvent_cb(e);
    }
}
void ui_event_pinmameDipButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinmameEvent_cb(e);
    }
}
void ui_event_pinmameAddEBallButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinmameEvent_cb(e);
    }
}
void ui_event_pinmameBangBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonPinmameEvent_cb(e);
    }
}
void ui_event_statusPingButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buttonStatusEvent_cb(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
