// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_PinVolTabPage;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_leftPanel19;
extern lv_obj_t * ui_pinvolglobal;
extern lv_obj_t * ui_Panel22;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_Panel24;
void ui_event_pinvolGlobalUpImgButton(lv_event_t * e);
extern lv_obj_t * ui_pinvolGlobalUpImgButton;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Panel25;
void ui_event_pinvolGlobalDownImgButton(lv_event_t * e);
extern lv_obj_t * ui_pinvolGlobalDownImgButton;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_Panel26;
void ui_event_pinvolGlobalMuteImgButton(lv_event_t * e);
extern lv_obj_t * ui_pinvolGlobalMuteImgButton;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Panel23;
void ui_event_pinvolGlobalNightModeButton(lv_event_t * e);
extern lv_obj_t * ui_pinvolGlobalNightModeButton;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_pinvoltable;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel8;
void ui_event_pinvolTableVolUpImgButton(lv_event_t * e);
extern lv_obj_t * ui_pinvolTableVolUpImgButton;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel9;
void ui_event_pinvolTableVolDownImgButton(lv_event_t * e);
extern lv_obj_t * ui_pinvolTableVolDownImgButton;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_rightPanel10;
extern lv_obj_t * ui_pinvoltable1;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Panel27;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_backglassPanel15;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Panel12;
void ui_event_pinvolSSFBgUpImgButton(lv_event_t * e);
extern lv_obj_t * ui_pinvolSSFBgUpImgButton;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel13;
void ui_event_pinvolSSFBgDownImgButton(lv_event_t * e);
extern lv_obj_t * ui_pinvolSSFBgDownImgButton;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_backglassPanel1;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Panel16;
void ui_event_pinvolSSFRearUpImgButton(lv_event_t * e);
extern lv_obj_t * ui_pinvolSSFRearUpImgButton;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Panel17;
void ui_event_pinvolSSFRearDownImgButton(lv_event_t * e);
extern lv_obj_t * ui_pinvolSSFRearDownImgButton;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_backglassPanel2;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Panel19;
void ui_event_pinvolSSFFrontUpImgButton(lv_event_t * e);
extern lv_obj_t * ui_pinvolSSFFrontUpImgButton;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Panel20;
void ui_event_pinvolSSFFrontDownImgButton(lv_event_t * e);
extern lv_obj_t * ui_pinvolSSFFrontDownImgButton;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_PinMameTabPage;
extern lv_obj_t * ui_Panel30;
extern lv_obj_t * ui_leftPanel;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel4;
void ui_event_pinmameEBBuyinButton(lv_event_t * e);
extern lv_obj_t * ui_pinmameEBBuyinButton;
extern lv_obj_t * ui_Label4;
void ui_event_pinmameCoin3Button(lv_event_t * e);
extern lv_obj_t * ui_pinmameCoin3Button;
extern lv_obj_t * ui_Label5;
void ui_event_pinmameCoin4Button(lv_event_t * e);
extern lv_obj_t * ui_pinmameCoin4Button;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Panel28;
void ui_event_pinmameUpButton(lv_event_t * e);
extern lv_obj_t * ui_pinmameUpButton;
extern lv_obj_t * ui_Label18;
void ui_event_pinmameDownButton(lv_event_t * e);
extern lv_obj_t * ui_pinmameDownButton;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Panel5;
void ui_event_pinmameDoorButton(lv_event_t * e);
extern lv_obj_t * ui_pinmameDoorButton;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Panel29;
void ui_event_pinmameEnterButton(lv_event_t * e);
extern lv_obj_t * ui_pinmameEnterButton;
extern lv_obj_t * ui_Label20;
void ui_event_pinmameCancelButton(lv_event_t * e);
extern lv_obj_t * ui_pinmameCancelButton;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_rightPanel;
extern lv_obj_t * ui_Panel31;
extern lv_obj_t * ui_leftPanel1;
void ui_event_pinmameShowOptsButton(lv_event_t * e);
extern lv_obj_t * ui_pinmameShowOptsButton;
extern lv_obj_t * ui_Label22;
void ui_event_pinmameResetEmuButton(lv_event_t * e);
extern lv_obj_t * ui_pinmameResetEmuButton;
extern lv_obj_t * ui_Label24;
void ui_event_pinmameWindowLockButton(lv_event_t * e);
extern lv_obj_t * ui_pinmameWindowLockButton;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
void ui_event_pinmameDisplaySizeButton(lv_event_t * e);
extern lv_obj_t * ui_pinmameDisplaySizeButton;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_rightPanel22;
void ui_event_pinmameShowKeysButton(lv_event_t * e);
extern lv_obj_t * ui_pinmameShowKeysButton;
extern lv_obj_t * ui_Label36;
void ui_event_pinmameDipButton(lv_event_t * e);
extern lv_obj_t * ui_pinmameDipButton;
extern lv_obj_t * ui_Label23;
void ui_event_pinmameAddEBallButton(lv_event_t * e);
extern lv_obj_t * ui_pinmameAddEBallButton;
extern lv_obj_t * ui_Label28;
void ui_event_pinmameBangBackButton(lv_event_t * e);
extern lv_obj_t * ui_pinmameBangBackButton;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_VPXTabPage;
extern lv_obj_t * ui_StatusTabPage;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel34;
extern lv_obj_t * ui_Panel36;
extern lv_obj_t * ui_Panel35;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_deviceNameLabel;
extern lv_obj_t * ui_Panel32;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_cabinetTempLabel;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Panel33;
extern lv_obj_t * ui_WiFiStatusImg;
extern lv_obj_t * ui_ssidLabel;
extern lv_obj_t * ui_statusMsgsTextArea;
extern lv_obj_t * ui_Panel37;
void ui_event_statusPingButton(lv_event_t * e);
extern lv_obj_t * ui_statusPingButton;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_volume_normal_icon_64_png);    // assets\Volume_Normal_Icon_64.png
LV_IMG_DECLARE(ui_img_volume_normal_icon_64_pressed_png);    // assets\Volume_Normal_Icon_64_pressed.png
LV_IMG_DECLARE(ui_img_volume_normal_red_icon_64_png);    // assets\Volume_Normal_Red_Icon_64.png
LV_IMG_DECLARE(ui_img_volume_normal_red_icon_64_pressed_png);    // assets\Volume_Normal_Red_Icon_64_pressed.png
LV_IMG_DECLARE(ui_img_volume_disabled_icon_64_png);    // assets\Volume_Disabled_Icon_64.png
LV_IMG_DECLARE(ui_img_volume_disabled_icon_64_pressed_png);    // assets\Volume_Disabled_Icon_64_pressed.png
LV_IMG_DECLARE(ui_img_1661985963);    // assets\dark-mode-64.png
LV_IMG_DECLARE(ui_img_494244644);    // assets\dark-mode-64_pressed.png
LV_IMG_DECLARE(ui_img_red_wifi_64_png);    // assets\red_wifi_64.png
LV_IMG_DECLARE(ui_img_green_wifi_64_png);    // assets\green_wifi_64.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
