// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "../../../main/lvgl_event_handler.h"

void buttonPinvolEvent_cb(lv_event_t * e)
{
	buttonPinvolCallback(e);
}


void buttonPinmameEvent_cb(lv_event_t * e)
{
	buttonPinmameCallback(e);
}

void buttonStatusEvent_cb(lv_event_t * e)
{
	buttonStatusCallback(e);
}

void buttonVPXEvent_cb(lv_event_t * e)
{
	buttonVPXCallback(e);
}
